# Generated by Django 4.0 on 2022-01-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lot', models.CharField(max_length=200)),
                ('nb_piece', models.IntegerField()),
                ('typologie', models.CharField(max_length=200)),
                ('prix_tva_reduite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_tva_normale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_HT', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_m2_HT', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_m2_TTC', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8)),
                ('etage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('orientation', models.CharField(max_length=200)),
                ('exterieur', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('nom_programme', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('departement', models.IntegerField()),
                ('date_fin_programme', models.CharField(max_length=200)),
                ('adresse_entiere', models.CharField(max_length=200)),
                ('promoteur', models.CharField(max_length=200)),
            ],
        ),
    ]
