# Generated by Django 4.0 on 2022-01-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0002_alter_bien_etage_alter_bien_prix_ht_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bien',
        ),
    ]
